version: '3'
services:
  crypto-trading:
    container_name: crypto-trading
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
    networks:
      net:
    ports:
      - "3002:3002"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
networks:
  net:
